### ISSUE TITLE
Make layout more responsive for mobile devices

### ISSUE THREAD

**Issue by escamoteur** [DevsHelpDevs/donation_tracker#2]
Currently the layout only works well on big screens. I honestly completely forgot that it will look much different on a mobile device.
So we probably need a different list item Widget for mobile in contrast to desktop.

I would like to give the layout package a try here please see

https://pub.dev/packages/layout

So anyone who likes, give it a shot and make this app a little bit prettier and better to use on mobile.

**Comment by jaumard** [comment]
I've created that one some time ago if it can help https://pub.dev/packages/proxy_layout ^^

**Comment by escamoteur** [comment]
looks also really nice

**Comment by Blazebrain** [comment]
Alright sir, on it.
